AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 15

Naming/VariableNumber:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'
